# Generated by Django 4.0.3 on 2022-04-04 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Watch',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('mac', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Sleep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('green', models.FloatField(blank=True, null=True)),
                ('red', models.FloatField(blank=True, null=True)),
                ('ir', models.FloatField(blank=True, null=True)),
                ('x', models.FloatField(blank=True, null=True)),
                ('y', models.FloatField(blank=True, null=True)),
                ('z', models.FloatField(blank=True, null=True)),
                ('sleep_index', models.IntegerField(blank=True, null=True)),
                ('freq', models.IntegerField()),
                ('created', models.DateTimeField(auto_now=True)),
                ('watch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch4', to='watch.watch')),
            ],
        ),
        migrations.CreateModel(
            name='PPG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('green', models.FloatField(blank=True, null=True)),
                ('red', models.FloatField(blank=True, null=True)),
                ('ir', models.FloatField(blank=True, null=True)),
                ('freq', models.IntegerField()),
                ('created', models.DateTimeField(auto_now=True)),
                ('watch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch1', to='watch.watch')),
            ],
        ),
        migrations.CreateModel(
            name='Gsensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_x', models.FloatField(blank=True, null=True)),
                ('acc_y', models.FloatField(blank=True, null=True)),
                ('acc_z', models.FloatField(blank=True, null=True)),
                ('gyr_x', models.FloatField(blank=True, null=True)),
                ('gyr_y', models.FloatField(blank=True, null=True)),
                ('gyr_z', models.FloatField(blank=True, null=True)),
                ('mag_x', models.FloatField(blank=True, null=True)),
                ('mag_y', models.FloatField(blank=True, null=True)),
                ('mag_z', models.FloatField(blank=True, null=True)),
                ('freq', models.IntegerField()),
                ('created', models.DateTimeField(auto_now=True)),
                ('watch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch3', to='watch.watch')),
            ],
        ),
        migrations.CreateModel(
            name='ECG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ecg', models.FloatField(blank=True, null=True)),
                ('mv', models.FloatField(blank=True, null=True)),
                ('freq', models.IntegerField()),
                ('created', models.DateTimeField(auto_now=True)),
                ('watch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch2', to='watch.watch')),
            ],
        ),
    ]
