# Generated by Django 4.0.3 on 2022-04-15 15:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Watch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('mac', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PPG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('green', models.FloatField(blank=True, null=True)),
                ('red', models.FloatField(blank=True, null=True)),
                ('ir', models.FloatField(blank=True, null=True)),
                ('freq', models.IntegerField()),
                ('created', models.DateTimeField(default=datetime.datetime(2022, 4, 15, 23, 34, 33, 654344))),
                ('watch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch1', to='watch.watch')),
            ],
        ),
        migrations.CreateModel(
            name='GYR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField(blank=True, null=True)),
                ('y', models.FloatField(blank=True, null=True)),
                ('z', models.FloatField(blank=True, null=True)),
                ('freq', models.IntegerField()),
                ('created', models.DateTimeField(default=datetime.datetime(2022, 4, 15, 23, 34, 33, 655064))),
                ('watch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch4', to='watch.watch')),
            ],
        ),
        migrations.CreateModel(
            name='ECG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ecg', models.FloatField(blank=True, null=True)),
                ('mv', models.FloatField(blank=True, null=True)),
                ('freq', models.IntegerField()),
                ('created', models.DateTimeField(default=datetime.datetime(2022, 4, 15, 23, 34, 33, 654577))),
                ('watch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch2', to='watch.watch')),
            ],
        ),
        migrations.CreateModel(
            name='ACC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField(blank=True, null=True)),
                ('y', models.FloatField(blank=True, null=True)),
                ('z', models.FloatField(blank=True, null=True)),
                ('freq', models.IntegerField()),
                ('created', models.DateTimeField(default=datetime.datetime(2022, 4, 15, 23, 34, 33, 654855))),
                ('watch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch3', to='watch.watch')),
            ],
        ),
    ]
