# Generated by Django 4.0.3 on 2022-04-16 15:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='acc',
            name='index',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ecg',
            name='index',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gyr',
            name='index',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ppg',
            name='index',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='acc',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 16, 23, 23, 6, 441069)),
        ),
        migrations.AlterField(
            model_name='ecg',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 16, 23, 23, 6, 440776)),
        ),
        migrations.AlterField(
            model_name='gyr',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 16, 23, 23, 6, 441292)),
        ),
        migrations.AlterField(
            model_name='ppg',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 16, 23, 23, 6, 440520)),
        ),
    ]
